services:
  # Backend API Service
  - type: web
    name: portfolio-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Only GEMINI API key needed - set manually in Render dashboard:
      - key: GEMINI_API_KEY

  # Frontend Static Site
  - type: web
    name: portfolio-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://portfolio-backend.onrender.com/api
